local M = {}

function M.setup(opts)
	opts = opts or {}
	vim.cmd([[cnoreabbrev Ga Git add]])
	vim.cmd([[cnoreabbrev Gaa Git add --all]])
	vim.cmd([[cnoreabbrev Gapa Git add --patch]])
	vim.cmd([[cnoreabbrev Gau Git add --update]])
	vim.cmd([[cnoreabbrev Gav Git add --verbose]])
	vim.cmd([[cnoreabbrev Gam Git am]])
	vim.cmd([[cnoreabbrev Gama Git am --abort]])
	vim.cmd([[cnoreabbrev Gamc Git am --continue]])
	vim.cmd([[cnoreabbrev Gamscp Git am --show-current-patch]])
	vim.cmd([[cnoreabbrev Gams Git am --skip]])
	vim.cmd([[cnoreabbrev Gap Git apply]])
	vim.cmd([[cnoreabbrev Gapt Git apply --3way]])
	vim.cmd([[cnoreabbrev Gbs Git bisect]])
	vim.cmd([[cnoreabbrev Gbsb Git bisect bad]])
	vim.cmd([[cnoreabbrev Gbsg Git bisect good]])
	vim.cmd([[cnoreabbrev Gbsn Git bisect new]])
	vim.cmd([[cnoreabbrev Gbso Git bisect old]])
	vim.cmd([[cnoreabbrev Gbsr Git bisect reset]])
	vim.cmd([[cnoreabbrev Gbss Git bisect start]])
	vim.cmd([[cnoreabbrev Gbl Git blame -w]])
	vim.cmd([[cnoreabbrev Gb	Git Branch]])
	vim.cmd([[cnoreabbrev Gba Git branch --all]])
	vim.cmd([[cnoreabbrev Gbd Git branch --delete]])
	vim.cmd([[cnoreabbrev GbD Git branch --delete --force]])
	vim.cmd([[cnoreabbrev Gbm Git branch --move]])
	vim.cmd([[cnoreabbrev Gbnm Git branch --no-merged]])
	vim.cmd([[cnoreabbrev Gbr Git branch --remote]])
	vim.cmd([[cnoreabbrev Ggsup Git branch --set-upstream-to=origin/$(git_current_branch)]])
	vim.cmd([[cnoreabbrev Gco Git checkout]])
	vim.cmd([[cnoreabbrev Gcor Git checkout --recurse-submodules]])
	vim.cmd([[cnoreabbrev Gcb Git checkout -b]])
	vim.cmd([[cnoreabbrev GcB Git checkout -B]])
	vim.cmd([[cnoreabbrev Gcd Git checkout $(git_develop_branch)]])
	vim.cmd([[cnoreabbrev Gcm Git checkout $(git_main_branch)]])
	vim.cmd([[cnoreabbrev Gcp Git cherry-pick]])
	vim.cmd([[cnoreabbrev Gcpa Git cherry-pick --abort]])
	vim.cmd([[cnoreabbrev Gcpc Git cherry-pick --continue]])
	vim.cmd([[cnoreabbrev Gclean Git clean --interactive -d]])
	vim.cmd([[cnoreabbrev Gcl Git clone --recurse-submodules]])
	vim.cmd([[cnoreabbrev Gclf Git clone --recursive --shallow-submodules --filter=blob:none --also-filter-submodules]])
	vim.cmd([[cnoreabbrev Gcam Git commit --all --message]])
	vim.cmd([[cnoreabbrev Gcas Git commit --all --signoff]])
	vim.cmd([[cnoreabbrev Gcasm Git commit --all --signoff --message]])
	vim.cmd([[cnoreabbrev Gcmsg Git commit --message]])
	vim.cmd([[cnoreabbrev Gcsm Git commit --signoff --message]])
	vim.cmd([[cnoreabbrev Gc	Git commit --verbose]])
	vim.cmd([[cnoreabbrev Gca Git commit --verbose --all]])
	-- vim.cmd([[cnoreabbrev Gca!	Git commit --verbose --all --amend]])
	-- vim.cmd([[cnoreabbrev Gcan !	git commit --verbose --all --no-edit --amend]])
	-- vim.cmd([[cnoreabbrev Gcans !	git commit --verbose --all --signoff --no-edit --amend]])
	-- vim.cmd([[cnoreabbrev Gcann !	git commit --verbose --all --date=now --no-edit --amend]])
	-- vim.cmd([[cnoreabbrev Gc! Git commit --verbose --amend]])
	vim.cmd([[cnoreabbrev Gcn Git commit --verbose --no-edit]])
	-- vim.cmd([[cnoreabbrev Gcn !	git commit --verbose --no-edit --amend]])
	vim.cmd([[cnoreabbrev Gcs Git commit -S]])
	vim.cmd([[cnoreabbrev Gcss Git commit -S -s]])
	vim.cmd([[cnoreabbrev Gcssm Git commit -S -s -m]])
	vim.cmd([[cnoreabbrev Gcf Git config --list]])
	vim.cmd([[cnoreabbrev Gcfu Git commit --fixup]])
	vim.cmd([[cnoreabbrev Gd    Git Diff]])
	vim.cmd([[cnoreabbrev Gdca Git diff --cached]])
	vim.cmd([[cnoreabbrev Gdcw Git diff --cached --word-diff]])
	vim.cmd([[cnoreabbrev Gds Git diff --staged]])
	vim.cmd([[cnoreabbrev Gdw Git diff --word-diff]])
	vim.cmd([[cnoreabbrev Gdup Git diff @{upstream}]])
	vim.cmd([[cnoreabbrev Gdnolock Git diff $@ ":(exclude)package-lock.json" ":(exclude)\*.lock"]])
	vim.cmd([[cnoreabbrev Gdt Git diff-tree --no-commit-id --name-only -r]])
	vim.cmd([[cnoreabbrev Gf	Git Fetch]])
	vim.cmd([[cnoreabbrev Gfa Git fetch --all --tags --prune]])
	vim.cmd([[cnoreabbrev Gfo Git fetch origin]])
	vim.cmd([[cnoreabbrev Gg	Git Gui citool]])
	vim.cmd([[cnoreabbrev Gga Git gui citool --amend]])
	vim.cmd([[cnoreabbrev Ghh Git help]])
	vim.cmd([[cnoreabbrev Glgg Git log --graph]])
	vim.cmd([[cnoreabbrev Glgga Git log --graph --decorate --all]])
	vim.cmd([[cnoreabbrev Glgm Git log --graph --max-count=10]])
	vim.cmd([[cnoreabbrev Glo Git log --oneline --decorate]])
	vim.cmd([[cnoreabbrev Glog Git log --oneline --decorate --graph]])
	vim.cmd([[cnoreabbrev Gloga Git log --oneline --decorate --graph --all]])
	vim.cmd([[cnoreabbrev Glp Git log --pretty=<format>]])
	vim.cmd([[cnoreabbrev Glg Git log --stat]])
	vim.cmd([[cnoreabbrev Glgp Git log --stat --patch]])
	vim.cmd([[cnoreabbrev Gm	Git Merge]])
	vim.cmd([[cnoreabbrev Gma Git merge --abort]])
	vim.cmd([[cnoreabbrev Gmc Git merge --continue]])
	vim.cmd([[cnoreabbrev Gms Git merge --squash]])
	vim.cmd([[cnoreabbrev Gmff Git merge --ff-only]])
	vim.cmd([[cnoreabbrev Gmom Git merge origin/$(git_main_branch)]])
	vim.cmd([[cnoreabbrev Gmum Git merge upstream/$(git_main_branch)]])
	vim.cmd([[cnoreabbrev Gmtl Git mergetool --no-prompt]])
	vim.cmd([[cnoreabbrev Gmtlvim Git mergetool --no-prompt --tool=vimdiff]])
	vim.cmd([[cnoreabbrev Gl	Git Pull]])
	vim.cmd([[cnoreabbrev Gpr Git pull --rebase]])
	vim.cmd([[cnoreabbrev Gprv Git pull --rebase -v]])
	vim.cmd([[cnoreabbrev Gpra Git pull --rebase --autostash]])
	vim.cmd([[cnoreabbrev Gprav Git pull --rebase --autostash -v]])
	vim.cmd([[cnoreabbrev Gprom Git pull --rebase origin $(git_main_branch)]])
	vim.cmd([[cnoreabbrev Gpromi Git pull --rebase=interactive origin $(git_main_branch)]])
	vim.cmd([[cnoreabbrev Gprum Git pull --rebase upstream $(git_main_branch)]])
	vim.cmd([[cnoreabbrev Gprumi Git pull --rebase=interactive upstream $(git_main_branch)]])
	vim.cmd([[cnoreabbrev Ggpull Git pull origin "$(git_current_branch)"]])
	vim.cmd([[cnoreabbrev Ggl Git pull origin $(current_branch)]])
	vim.cmd([[cnoreabbrev Gluc Git pull upstream $(git_current_branch)]])
	vim.cmd([[cnoreabbrev Glum Git pull upstream $(git_main_branch)]])
	vim.cmd([[cnoreabbrev Gp	Git push]])
	vim.cmd([[cnoreabbrev Gpd Git push --dry-run]])
	-- vim.cmd([[cnoreabbrev Gpf !	git push --force]])
	vim.cmd([[cnoreabbrev Ggf Git push --force origin $(current_branch)]])
	vim.cmd([[cnoreabbrev Ggfl Git push --force-with-lease origin $(current_branch)]])
	vim.cmd([[cnoreabbrev Gpsup Git push --set-upstream origin $(git_current_branch)]])
	vim.cmd([[cnoreabbrev Gpv Git push --verbose]])
	vim.cmd([[cnoreabbrev Gpoat Git push origin --all && git push origin --tags]])
	vim.cmd([[cnoreabbrev Gpod Git push origin --delete]])
	vim.cmd([[cnoreabbrev Ggpush Git push origin "$(git_current_branch)"]])
	vim.cmd([[cnoreabbrev Ggp Git push origin $(current_branch)]])
	vim.cmd([[cnoreabbrev Gpu Git push upstream]])
	vim.cmd([[cnoreabbrev Grb Git rebase]])
	vim.cmd([[cnoreabbrev Grba Git rebase --abort]])
	vim.cmd([[cnoreabbrev Grbc Git rebase --continue]])
	vim.cmd([[cnoreabbrev Grbi Git rebase --interactive]])
	vim.cmd([[cnoreabbrev Grbo Git rebase --onto]])
	vim.cmd([[cnoreabbrev Grbs Git rebase --skip]])
	vim.cmd([[cnoreabbrev Grbd Git rebase $(git_develop_branch)]])
	vim.cmd([[cnoreabbrev Grbm Git rebase $(git_main_branch)]])
	vim.cmd([[cnoreabbrev Grbom Git rebase origin/$(git_main_branch)]])
	vim.cmd([[cnoreabbrev Grbum Git rebase upstream/$(git_main_branch)]])
	vim.cmd([[cnoreabbrev Grf Git reflog]])
	vim.cmd([[cnoreabbrev Gr	Git remote]])
	vim.cmd([[cnoreabbrev Grv Git remote --verbose]])
	vim.cmd([[cnoreabbrev Gra Git remote add]])
	vim.cmd([[cnoreabbrev Grrm Git remote remove]])
	vim.cmd([[cnoreabbrev Grmv Git remote rename]])
	vim.cmd([[cnoreabbrev Grset Git remote set-url]])
	vim.cmd([[cnoreabbrev Grup Git remote update]])
	vim.cmd([[cnoreabbrev Grh Git reset]])
	vim.cmd([[cnoreabbrev Gru Git reset --]])
	vim.cmd([[cnoreabbrev Grhh Git reset --hard]])
	vim.cmd([[cnoreabbrev Grhk Git reset --keep]])
	vim.cmd([[cnoreabbrev Grhs Git reset --soft]])
	vim.cmd([[cnoreabbrev Gpristine Git reset --hard && git clean --force -dfx]])
	vim.cmd([[cnoreabbrev Gwipe Git reset --hard && git clean --force -df]])
	vim.cmd([[cnoreabbrev Groh Git reset origin/$(git_current_branch) --hard]])
	vim.cmd([[cnoreabbrev Grs Git restore]])
	vim.cmd([[cnoreabbrev Grss Git restore --source]])
	vim.cmd([[cnoreabbrev Grst Git restore --staged]])
	vim.cmd([[cnoreabbrev Grev Git revert]])
	vim.cmd([[cnoreabbrev Grm Git rm]])
	vim.cmd([[cnoreabbrev Grmc Git rm --cached]])
	vim.cmd([[cnoreabbrev Gcount Git shortlog --summary -n]])
	vim.cmd([[cnoreabbrev Gsh Git show]])
	vim.cmd([[cnoreabbrev Gsps Git show --pretty=short --show-signature]])
	vim.cmd([[cnoreabbrev Gstall Git stash --all]])
	vim.cmd([[cnoreabbrev Gstu Git stash --include-untracked]])
	vim.cmd([[cnoreabbrev Gstaa Git stash apply]])
	vim.cmd([[cnoreabbrev Gstc Git stash clear]])
	vim.cmd([[cnoreabbrev Gstd Git stash drop]])
	vim.cmd([[cnoreabbrev Gstl Git stash list]])
	vim.cmd([[cnoreabbrev Gstp Git stash pop]])
	vim.cmd([[cnoreabbrev Gst Git status]])
	vim.cmd([[cnoreabbrev Gss Git status --short]])
	vim.cmd([[cnoreabbrev Gsb Git status --short -b]])
	vim.cmd([[cnoreabbrev Gsi Git submodule init]])
	vim.cmd([[cnoreabbrev Gsu Git submodule update]])
	vim.cmd([[cnoreabbrev Gsd Git svn dcommit]])
	-- vim.cmd([[cnoreabbrev Git -svn-dcommit-push	git svn dcommit && git push github $(git_main_branch):svntrunk]])
	vim.cmd([[cnoreabbrev Gsr Git svn rebase]])
	vim.cmd([[cnoreabbrev Gsw Git switch]])
	vim.cmd([[cnoreabbrev Gswc Git switch -c]])
	vim.cmd([[cnoreabbrev Gswd Git switch $(git_develop_branch)]])
	vim.cmd([[cnoreabbrev Gswm Git switch $(git_main_branch)]])
	vim.cmd([[cnoreabbrev Gta Git tag --annotate]])
	vim.cmd([[cnoreabbrev Gts Git tag -s]])
	vim.cmd([[cnoreabbrev Gignore Git update-index --assume-unchanged]])
	vim.cmd([[cnoreabbrev Gunignore Git update-index --no-assume-unchanged]])
	vim.cmd([[cnoreabbrev Gwch Git log --patch --abbrev-commit --pretty=medium --raw]])
	vim.cmd([[cnoreabbrev Gwt Git worktree]])
	vim.cmd([[cnoreabbrev Gwtls Git worktree list]])
	vim.cmd([[cnoreabbrev Gwtmv Git worktree move]])
	vim.cmd([[cnoreabbrev Gwtrm Git worktree remove]])
end

return M
